# Generated by Django 4.2.4 on 2024-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_supplier_contact_info_supplier_ab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ab_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
