# Generated by Django 4.2.4 on 2024-08-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_sellprice_enterprisedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcategory',
            name='enterprise',
        ),
        migrations.AlterField(
            model_name='client',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='inventory.enterprise'),
        ),
    ]
