# Generated by Django 4.2.4 on 2024-08-07 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_clientcategory_enterprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success')], default='created', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='inventory.enterprise')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='with_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bills', to='inventory.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sell_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sellprice')),
            ],
        ),
    ]
