# Generated by Django 4.2.4 on 2024-08-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='product_code',
        ),
    ]
