# Generated by Django 4.2.4 on 2024-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_variant_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
    ]
