# Generated by Django 4.2.4 on 2024-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbill',
            name='variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
