# Generated by Django 4.2.4 on 2024-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_productbill_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
