# Generated by Django 4.2.4 on 2024-08-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
