# Generated by Django 4.2.4 on 2024-08-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_employee_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Enterprise',
            new_name='enterprise',
        ),
    ]
