# Generated by Django 4.2.4 on 2024-08-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_rename_enterprise_employee_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='inventory.employee'),
        ),
    ]
