# Generated by Django 4.2.4 on 2024-08-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_employee_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategory',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salespoint'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.salespoint'),
        ),
    ]
