# Generated by Django 4.2.4 on 2024-08-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_client_number_alter_client_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
