# Generated by Django 4.2.4 on 2024-08-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcategory',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_category', to='inventory.enterprise'),
        ),
    ]
