# Generated by Django 4.2.4 on 2024-08-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packaging')),
            ],
            options={
                'verbose_name': 'Recorded Packaging',
                'verbose_name_plural': 'Recorded Packaging',
            },
        ),
    ]
