# Generated by Django 4.2.4 on 2024-08-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_remove_packaging_is_full_packaging_empty_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name': 'Packaging'},
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packaging'),
        ),
        migrations.AlterField(
            model_name='productbill',
            name='sell_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sellprice'),
        ),
    ]
