# Generated by Django 4.2.4 on 2024-08-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_packaging_options_product_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProductBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('record', models.PositiveIntegerField(default=0)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packaging')),
                ('product_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_product_bill', to='inventory.productbill')),
            ],
            options={
                'verbose_name': 'Package Product Bill',
                'verbose_name_plural': 'Package Product Bills',
            },
        ),
    ]
