# Generated by Django 4.2.4 on 2024-08-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_packageproductbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
            preserve_default=False,
        ),
    ]
