# Generated by Django 4.2.4 on 2024-08-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_packaging_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespoint',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.enterprise'),
        ),
    ]
