# Generated by Django 4.2.4 on 2024-08-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_bill_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('quantity_changed', models.PositiveIntegerField()),
                ('full_quantity_before', models.PositiveIntegerField()),
                ('empty_quantity_before', models.PositiveIntegerField()),
                ('full_quantity_after', models.PositiveIntegerField()),
                ('empty_quantity_after', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.packaging')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salespoint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
