# Generated by Django 4.2.4 on 2024-08-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_packaginghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginghistory',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.bill'),
        ),
        migrations.AddField(
            model_name='packaginghistory',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.variant'),
        ),
    ]
